// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNIpEyVWRT_AGHSKF2R-C2F3jllaJOQRk',
    appId: '1:1087935518273:web:0a17bb44327cddee4998c0',
    messagingSenderId: '1087935518273',
    projectId: 'fasum-app-22b2a',
    authDomain: 'fasum-app-22b2a.firebaseapp.com',
    databaseURL: 'https://fasum-app-22b2a-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-22b2a.firebasestorage.app',
    measurementId: 'G-J50Z2L25KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdAY6YL8kb9Y8GuZad55O3xpza0mhzol0',
    appId: '1:1087935518273:android:ca1dcc6cb55f63914998c0',
    messagingSenderId: '1087935518273',
    projectId: 'fasum-app-22b2a',
    databaseURL: 'https://fasum-app-22b2a-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-22b2a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNIpEyVWRT_AGHSKF2R-C2F3jllaJOQRk',
    appId: '1:1087935518273:web:7820cc7ec69c2a504998c0',
    messagingSenderId: '1087935518273',
    projectId: 'fasum-app-22b2a',
    authDomain: 'fasum-app-22b2a.firebaseapp.com',
    databaseURL: 'https://fasum-app-22b2a-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-22b2a.firebasestorage.app',
    measurementId: 'G-7MHZH6RS6Q',
  );

}