// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBv0oV8fPt8YQsqqsCCC8L-wk1IlLTqzg',
    appId: '1:770936980259:web:6dcd440b3c0df423fbc296',
    messagingSenderId: '770936980259',
    projectId: 'first-app-59150',
    authDomain: 'first-app-59150.firebaseapp.com',
    databaseURL: 'https://first-app-59150-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-59150.firebasestorage.app',
    measurementId: 'G-QGBMJ1PM8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0w9xProvgcjouMmvPbOL6p64QPIMc9j0',
    appId: '1:770936980259:android:eca49f0027b0914afbc296',
    messagingSenderId: '770936980259',
    projectId: 'first-app-59150',
    databaseURL: 'https://first-app-59150-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-59150.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBv0oV8fPt8YQsqqsCCC8L-wk1IlLTqzg',
    appId: '1:770936980259:web:f106c45876758b11fbc296',
    messagingSenderId: '770936980259',
    projectId: 'first-app-59150',
    authDomain: 'first-app-59150.firebaseapp.com',
    databaseURL: 'https://first-app-59150-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-59150.firebasestorage.app',
    measurementId: 'G-N4CKQMZQYC',
  );
}
